name: repo maintenance

on:
  schedule:
    - cron: "0 12 * * 1" # every Monday at 12am UTC (4am PST)
  workflow_dispatch:

jobs:
  bump_submodules:
    name: bump_submodules
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/commaai/openpilot-base:latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: bump submodules
      run: |
        git config --global --add safe.directory '*'
        git -c submodule."tinygrad".update=none submodule update --remote
        git add .
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5
      with:
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: bump submodules
        title: 'Bump submodules'
        branch: auto-bump-submodules
        base: master
        delete-branch: true
        body: 'Automatic PR from repo-maintenance -> bump_submodules'
  package_updates:
    name: package_updates
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/commaai/openpilot-base:latest
    steps:
    - uses: actions/checkout@v4
    - name: poetry lock
      run: |
        pip install poetry
        poetry lock
    - name: pre-commit autoupdate
      run: |
        git config --global --add safe.directory '*'
        pre-commit autoupdate
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5
      with:
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: Update Python packages and pre-commit hooks
        title: 'Update Python packages and pre-commit hooks'
        branch: auto-package-updates
        base: master
        delete-branch: true
        body: 'Automatic PR from repo-maintenance -> package_updates'
